version: '3.1'
services:
  app:
     build: ./
     command: npm run dev
     container_name: app
     ports:
       - "3333:3333"
     depends_on:
       - mysql
     restart: always
     environment:
       - DATABASE_HOST=db
     restart: always
     volumes:
       - .:/usr/app
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elpatron
    volumes:
       - .:/usr/mysql
    ports:
       - 3306:3306   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:81
  nginx:
    image: nginx:1.13
    volumes:
      - "./var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: ./www
    volumes:
      - "./var/www/html"
    ports:
      - "9000:9000"
   
   